cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'zsh'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'git'
brew 'hub'
brew 'openssl'
#brew 'ruby-build'
brew 'rbenv'
#brew 'python-build'
brew 'pyenv'
#brew 'nvm'
brew 'elixir'
brew 'wget'
brew 'heroku'
brew 'watchman'
brew 'watch'
brew 'jq'

cask 'docker'
cask 'rubymine'
cask 'intellij-idea'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'java'
cask 'slack'
cask 'discord'
cask 'transmission'
cask 'vlc'
cask 'spotify'
cask 'keka'
